apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: hello-world-container
        image: public.ecr.aws/z3r2g0a5/hello-world-app:latest
        ports:
        - containerPort: 3000
